# Generated by Django 4.0.4 on 2022-05-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faceemotion',
            old_name='img',
            new_name='image',
        ),
    ]
